version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
    ports:
      - "8080:8080"
    command: start-dev --verbose
    depends_on:
      - keycloak-postgres

  keycloak-postgres:
    image: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  backend-db:
    image: postgres
    expose:
     - "5433"
    ports:
      - "5433:5433"
    environment:
      POSTGRES_DB: api
      POSTGRES_USER: api
      POSTGRES_PASSWORD: password
    command: -p 5433

  backend:
    build: ./PersonApi
    ports:
      - "4001:8080"
    depends_on:
      - keycloak
      - backend-db

  client:
    build: ./person-client
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
    driver: local

networks:
  default:
    driver: bridge